# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57ee6537122d86105a32f8674c8f77c0eca10f39e94ff353edca0ee9cbafbf3512a238a146f9012a8f1ec3a0e911eefbd3807dbd1a4e75d906ab8304a503c51a

test:
  secret_key_base: f1a48917346cc2cc0cae8d0cf2fe7e58dd3ab7d2fe81130d450cb742da1bf5c455471f736fe2553d15d0449550ea3ecf657df437ea535d7b3e4f2b83c8cc30bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
